### ISSUE TITLE
fmt 1.5.1 failing

### ISSUE THREAD

**Issue by ncordon** [ohnosequences/buildconf#4]
Commit [edeb85](https://github.com/ohnosequences/buildconf/commit/edeb8500dbfdc40a6407b38d5551dbd37f658bb7) changed `fmtVersion` to 1.5.1. This new version does not seem to work (documented in https://github.com/lucidsoftware/neo-sbt-scalafmt/issues/69).

**Comment by eparejatobes** [comment]
We should update once https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/72 gets merged.

**Comment by laughedelic** [comment]
Notice that the official sbt client got a big revamp and is probably better than neo-version. Worths trying once 1.6.0 is released (currently in RC4).
